import type {
  Endpoint,
  Isochrone,
  IsochroneRequest,
  Matrix,
  Route,
  RouteDirectionsRequest,
  RouteMatrixRequest
} from "@mapos/contracts";
import {
  type AdapterContext,
  type IsochroneCapability,
  MapServiceError,
  MapServiceValidationError,
  type RoutingCapability,
  ValhallaIsochroneResponseSchema,
  ValhallaMatrixResponseSchema,
  ValhallaRouteResponseSchema,
  buildIsochroneRequestBody,
  buildMatrixRequestBody,
  buildRouteRequestBody,
  parseIsochroneResponse,
  parseMatrixResponse,
  parseRouteResponse
} from "@mapos/service-adapters";
import type { Actor } from "@valhallajs/valhallajs";
import { listInstalledRegions, regionCoveringPoints, regionsContaining } from "./installed-regions";
import configTemplate from "./valhalla-config.template.json";

/**
 * Offline routing/isochrones/matrix against a downloaded `valhalla_tiles.tar`,
 * run **in-process** via the `@valhallajs/valhallajs` native addon (no Docker, no
 * HTTP subprocess — the only model that also works on iOS later). `Endpoint.url`
 * carries the absolute path to the region's `valhalla_tiles.tar`; `resolve()` puts
 * it there.
 *
 * The native actor speaks the same request/response JSON as the Valhalla HTTP
 * server, so request-building and response-parsing are shared with the HTTP
 * adapter (`@mapos/service-adapters`) — only the transport differs (`actor.*` vs
 * `fetch`). Output is therefore identical whether the user is online or offline.
 *
 * Config: Valhalla rejects a minimal config (it needs the full `service_limits`
 * tree etc.), so we ship a full template generated by `valhalla_build_config`
 * (`valhalla-config.template.json`) and only rewrite `mjolnir.tile_extract` to the
 * region tar at runtime. This keeps the runtime path subprocess-free (we never
 * shell out to the bundled `valhalla_build_config`, which wouldn't work from
 * inside an asar anyway).
 */

// One Actor per region tar, reused across calls. The promise is cached so
// concurrent first-calls share a single (potentially slow) initialisation; a
// failed init is evicted so the next call can retry.
const actors = new Map<string, Promise<Actor>>();

function buildConfig(tarPath: string): Record<string, unknown> {
  const cfg = structuredClone(configTemplate) as Record<string, unknown>;
  const mjolnir = cfg.mjolnir as Record<string, unknown>;
  mjolnir.tile_extract = tarPath;
  // Force reads from the .tar extract. Setting undefined (rather than "") drops
  // the key when the Actor JSON-stringifies the config, so Valhalla doesn't treat
  // an empty string as a (missing) tile directory.
  mjolnir.tile_dir = undefined;
  return cfg;
}

function getActor(tarPath: string): Promise<Actor> {
  let actor = actors.get(tarPath);
  if (!actor) {
    // Dynamic import keeps the 10 MB native addon off the app-startup path — it
    // dlopens on the first offline routing call instead of at module load.
    actor = import("@valhallajs/valhallajs")
      .then(({ Actor }) => new Actor(buildConfig(tarPath)))
      .catch((err) => {
        actors.delete(tarPath);
        throw err;
      });
    actors.set(tarPath, actor);
  }
  return actor;
}

/** Close cached Actors — call when the set of downloaded regions changes. */
export function closeOfflineRoutingActors(): void {
  // The binding exposes no explicit dispose; dropping references lets the native
  // tile extract be unmapped by GC.
  actors.clear();
}

/**
 * Pick the Valhalla tar of the downloaded pack covering `(lng, lat)`. Valhalla
 * tiles are per-region and can't be merged, so we route within the pack that
 * contains the origin; a point outside every downloaded pack can't be routed
 * offline. `ep.url` is the regions directory.
 */
function pickValhallaTar(regionsDir: string, lng: number, lat: number): string {
  const withValhalla = listInstalledRegions(regionsDir).filter((r) => r.valhalla);
  const hit = regionsContaining(withValhalla, lng, lat, { failOpen: false })[0];
  if (!hit?.valhalla) {
    throw new MapServiceError("No downloaded region covers this location", {
      status: 404,
      url: regionsDir
    });
  }
  return hit.valhalla;
}

/**
 * Pick the single Valhalla tar covering an *entire* route/matrix. Because graphs can't be
 * joined, every point must sit in one pack — so we resolve the smallest pack covering them all
 * up front rather than picking the origin's pack and letting Valhalla fail deep in the route
 * with a misleading "no suitable edges" once the path leaves that pack's tiles. A trip that no
 * single pack covers is cross-region and can't be routed offline yet.
 */
function pickValhallaTarForRoute(
  regionsDir: string,
  points: { lng: number; lat: number }[]
): string {
  const withValhalla = listInstalledRegions(regionsDir).filter((r) => r.valhalla);
  const hit = regionCoveringPoints(withValhalla, points);
  if (hit?.valhalla) return hit.valhalla;
  // Both messages match the panel's offline signature and surface as needs-region; the split
  // just makes the log say whether the start itself is uncovered or the trip leaves its pack.
  const originCovered = points[0] && regionCoveringPoints(withValhalla, [points[0]]);
  throw new MapServiceError(
    originCovered
      ? "No downloaded region covers this whole route"
      : "No downloaded region covers this location",
    { status: 404, url: regionsDir }
  );
}

function toServiceError(url: string, err: unknown): MapServiceError | MapServiceValidationError {
  if (err instanceof MapServiceError || err instanceof MapServiceValidationError) return err;
  const message = err instanceof Error ? err.message : String(err);
  return new MapServiceError(`Local Valhalla error: ${message}`, { status: 500, url });
}

// Note: `ctx.signal` is ignored — the native actor call can't be aborted
// mid-flight. Local routes are fast, so this is acceptable.

async function directions(
  req: RouteDirectionsRequest,
  ep: Endpoint,
  _ctx: AdapterContext = {}
): Promise<Route> {
  const tarPath = pickValhallaTarForRoute(ep.url, req.locations);
  let raw: unknown;
  try {
    const actor = await getActor(tarPath);
    raw = await actor.route(buildRouteRequestBody(req));
  } catch (err) {
    throw toServiceError(tarPath, err);
  }
  const parsed = ValhallaRouteResponseSchema.safeParse(raw);
  if (!parsed.success) {
    throw new MapServiceValidationError("Local Valhalla /route failed schema validation", {
      url: tarPath,
      zodError: parsed.error
    });
  }
  return parseRouteResponse(parsed.data);
}

async function matrix(
  req: RouteMatrixRequest,
  ep: Endpoint,
  _ctx: AdapterContext = {}
): Promise<Matrix> {
  const tarPath = pickValhallaTarForRoute(ep.url, [...req.sources, ...req.targets]);
  let raw: unknown;
  try {
    const actor = await getActor(tarPath);
    raw = await actor.matrix(buildMatrixRequestBody(req));
  } catch (err) {
    throw toServiceError(tarPath, err);
  }
  const parsed = ValhallaMatrixResponseSchema.safeParse(raw);
  if (!parsed.success) {
    throw new MapServiceValidationError("Local Valhalla /matrix failed schema validation", {
      url: tarPath,
      zodError: parsed.error
    });
  }
  return parseMatrixResponse(parsed.data, req);
}

async function contours(
  req: IsochroneRequest,
  ep: Endpoint,
  _ctx: AdapterContext = {}
): Promise<Isochrone> {
  const tarPath = pickValhallaTar(ep.url, req.location.lng, req.location.lat);
  let raw: unknown;
  try {
    const actor = await getActor(tarPath);
    raw = await actor.isochrone(buildIsochroneRequestBody(req));
  } catch (err) {
    throw toServiceError(tarPath, err);
  }
  const parsed = ValhallaIsochroneResponseSchema.safeParse(raw);
  if (!parsed.success) {
    throw new MapServiceValidationError("Local Valhalla /isochrone failed schema validation", {
      url: tarPath,
      zodError: parsed.error
    });
  }
  return parseIsochroneResponse(parsed.data);
}

export const offlineRouting: RoutingCapability = { directions, matrix };
export const offlineIsochrones: IsochroneCapability = { contours };
